import type { Expense } from './types';

export function formatCurrency(amount: number, currency = 'USD', symbol?: string) {
  const options: Intl.NumberFormatOptions = {
    style: 'currency',
    currency: currency,
  };

  if (symbol) {
    options.currencyDisplay = 'symbol';
  }

  const formatter = new Intl.NumberFormat('en-US', options);
  let formatted = formatter.format(amount);

  if (symbol && formatted.includes(currency)) {
    // Some browsers may still show the code, so we replace it.
    const currencySymbols: { [key: string]: string } = {
      'USD': '$',
      'INR': '₹',
      'EUR': '€',
    };
    const correctSymbol = currencySymbols[currency] || symbol;
    
    // Find all possible currency codes/symbols generated by Intl and replace them
    const knownSymbols = Object.values(currencySymbols).join('|');
    const regex = new RegExp(`(${knownSymbols}|${currency})`, 'g');
    
    let replaced = false;
    formatted = formatted.replace(regex, (match) => {
      if (!replaced) {
        replaced = true;
        return correctSymbol;
      }
      return ''; // Remove subsequent occurrences if any
    }).trim();

    // If for some reason the symbol is at the end, make sure there's no double spacing.
    formatted = formatted.replace(/\s+/, ' ');
  } else if (symbol) {
    // Fallback for when currency code isn't replaced
    const defaultSymbol = new Intl.NumberFormat('en-US', { style: 'currency', currency, currencyDisplay: 'symbol' }).format(0).replace(/[0-9.,]/g, '').trim();
    if(formatted.includes(defaultSymbol)){
        formatted = formatted.replace(defaultSymbol, symbol);
    }
  }


  return formatted;
}

export function exportToCsv(expenses: Expense[], fileName: string) {
  if (typeof window === 'undefined') return;

  const headers = ['ID', 'Date', 'Description', 'Amount', 'Category'];
  const csvRows = [
    headers.join(','),
    ...expenses.map(expense =>
      [
        expense.id,
        expense.date.toISOString().split('T')[0],
        `"${expense.description.replace(/"/g, '""')}"`,
        expense.amount,
        expense.category,
      ].join(',')
    ),
  ];

  const csvString = csvRows.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', fileName);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}
